### ISSUE TITLE
RuntimeException Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x80010 pkg=com.**** (has extras) } in com.ReactNativeBlobUtil.i@5ff20d9

### ISSUE THREAD

**Issue by Saad-Bashar** [RonRadtke/react-native-blob-util#179]
Hi, I am having this crash on my production android app. It seems to occur on certain devices, specifically with OPPO android. The first time download is fine but when user again download the file second time, the app crashes with this error message. Most probably it is the same issue with the previous library, https://github.com/joltup/rn-fetch-blob/issues/236.

Any suggestion or solution to it would be super helpful, thanks!

**Comment by RonRadtke** [comment]
Might be the same issue like this here:
https://github.com/RonRadtke/react-native-blob-util/issues/113
End next week I will have some time to see if I can fix it.
Do you have a device you can reproduce the error with? So far I couldn't

**Comment by KarlosQ** [comment]
> Do you have a device you can reproduce the error with? So far I couldn't

For me the devices are (OPPO and Realme):
- Reno 4Z 5G (CPH2065)
- realme 8 Pro (RMX3081)
- CPH2145

Thanks

**Comment by RonRadtke** [comment]
Got hopefully fixed in 0.16.3 @KarlosQ

**Comment by sarafcredable** [comment]
Still facing the issue even after updating the package to the latest

**Comment by Saad-Bashar** [comment]
Oh shoot, I am going to release the latest version and monitor the logs from sentry.

**Comment by RonRadtke** [comment]
Yeah I screwed that update up and forgot a single line of code... sorry for that

**Comment by ics-india-tech** [comment]
I am also facing this issue in the OnePlus Nord phone too. Kindly help @RonRadtke

**Comment by RonRadtke** [comment]
#188 should fix the bug I missed with the last update and therefor hopefully fixes this issue.

**Comment by ics-india-tech** [comment]
Thanks @RonRadtke Issue resolved. You saved my day. Thanks a ton once again.

**Comment by RaviDhakadDoodle** [comment]
Hello @RonRadtke 
I am still facing the same issue on the production build
```
Fatal Exception: java.lang.RuntimeException
Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x80010 pkg=com.example.android (has extras) } in com.ReactNativeBlobUtil.ReactNativeBlobUtilReq@e9b1b57
```
`react-native 0.66.3`
`"react-native-blob-util": "^0.17.0"`

**Device** 
Android 13
OnePlus 8

could you please help me with this? Thanks.

**Comment by KarlosQ** [comment]
> Hello @RonRadtke I am still facing the same issue on the production build
> 
> ```
> Fatal Exception: java.lang.RuntimeException
> Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x80010 pkg=com.example.android (has extras) } in com.ReactNativeBlobUtil.ReactNativeBlobUtilReq@e9b1b57
> ```
> 
> `react-native 0.66.3` `"react-native-blob-util": "^0.17.0"`
> 
> **Device** Android 13 OnePlus 8
> 
> could you please help me with this? Thanks.

Same here:

`react-native 0.71.3`
`react-native-blob-util: 0.17.1`

Device
Android 12
Realme 8 Pro

**Comment by widianapw** [comment]
Hi, I still facing this issue on version 0.17.3.
device: Realme 7 Android 12.

**Comment by dickyywfr** [comment]
still facing this issue too on version 0.17.2
device: Realme 5 Android 10

**Comment by claudiozam** [comment]
Same issue
Samsung Galaxy S22+
Android 13
RN 0.71.11
react-native-blob-util ^0.18.2

**Comment by sebas21** [comment]
Is there currently a solution? .. ty

**Comment by fcaldarelli** [comment]
Duplicated of https://github.com/joltup/rn-fetch-blob/issues/236
