### ISSUE TITLE
Not getting headers , status  , respType , redirects in the respInfo of response  occasionally in iOS.

### ISSUE THREAD

**Issue by rifad4u** [RonRadtke/react-native-blob-util#236]
Not getting headers , status  , respType , redirects in the respInfo of response occasionally in iOS. on that time getting "rnfbEncode" only in the respInfo.

i'm attaching 2 screenshots here , both screenshots are responsible for same api and getting the same data in the data part , but the respInfo are not getting properly.
<img width="527" alt="Screenshot 2023-03-22 at 2 42 24 PM" src="https://user-images.githubusercontent.com/37132763/226855946-21c51abf-fd66-4186-892e-67efac94c7d1.png">
<img width="534" alt="Screenshot 2023-03-22 at 2 42 53 PM" src="https://user-images.githubusercontent.com/37132763/226855963-4ae36ad3-307d-4b0a-904c-54385bb9847b.png">

**Comment by kelly-torum** [comment]
hi @RonRadtke, can you check this please? Getting only `rnfbEncode` in `respInfo` quite often recently

**Comment by kelly-torum** [comment]
How do you get the proper response header on iOS?

**Comment by rifad4u** [comment]
> How do you get the proper response header on iOS?

Use 0.17.1th version

**Comment by kelly-torum** [comment]
> Use 0.17.1th version

@rifad4u I'm using 0.17.1 version. do you any other workarounds to get response headers? @RonRadtke @cjpete 😓

**Comment by RonRadtke** [comment]
Are you using libraries like RNN or maybe two navigators (button tabs + stack) or so?
I could imagine that there are problems if the root view can't be accessed and therfor the bridge might be null. That could ultimatley lead to events not being sent to JS correctly.

**Comment by rifad4u** [comment]
@RonRadtke Then y this happening occasionally only, if that is the case then it should happen every time , right?

**Comment by RonRadtke** [comment]
@rifad4u that's right, except if you're changing navigators somewhen during the life cycle.

But I honselty don't have a better idea right know either. I might be solved once I rewrote the whole vent system to a newer and hopefully more stable system using modern APIs / classes

**Comment by rifad4u** [comment]
@RonRadtke in my case i'm facing this while opening the application only , not happening in between and it is not replicating if i close and relaunch the application.

**Comment by RonRadtke** [comment]
@rifad4u it sounds wired as a behaviour.
I'm sorry but I currently don't have an explanation for it.
If you have the chance it would be great to try to debug it, I can't reproduce it in my app yet.
Would be good to know if the bridge / eventDispatcher are set up correctly or if these are not set correctly. And if not, why...

**Comment by gkueny** [comment]
Hi @RonRadtke,

We have the same issue on our side. We use `react-native-navigation`.

After some tests, I can track the issue from this change => https://github.com/RonRadtke/react-native-blob-util/commit/6290b21c3b5e60626a19bb6ea43f1579e15a8626

It's seem like:
- `rootView.bridge.eventDispatcher`  => can cause some crash at startup (we had them when we was on `0.70.1`)
- `bridge.eventDispatcher;` => is not reliable & can lost some events

I will try to set up some minimal reproduction.

**Comment by timjbray** [comment]
We're having the exact same issue on 0.17.3. Downgrading to 0.17.1 fixes the issue for us.

**Comment by RonRadtke** [comment]
I managed to reproduce it now in a local app bt unsure yet how to fix it

**Comment by matthewmturner** [comment]
Had the same issue and downgrading to 0.17.1 worked for me as well

**Comment by RonRadtke** [comment]
@cjpete could you test if the eventDispatcher is set and maybe if you get a bridge in  https://github.com/RonRadtke/react-native-blob-util/blob/132051c1204051f5148a0b4bfede00ed99f47c44/ios/ReactNativeBlobUtil/ReactNativeBlobUtil.mm#L71 ?
Sadly my repro for reproduction was a fail and I'm still struggling to reproduce it....

**Comment by RonRadtke** [comment]
Any new Informationen?
Anyone?
Could it be that it only happens when the appnis in the background or any idea based on yours app usage pattern?
I'm currently rewriting the whole event handling structure but i would feel better about it if i know where the problem currently is

**Comment by emelyanova** [comment]
@RonRadtke, we do experience the same issue on 0.17.3 and we send multipart/form-data to the Java backend. It happens when the app is in the foreground and can be reproduced both on the device and the simulator. We tried on devices with ios versions 16.2 and 15.7, but an android app was working well.  There are no clear steps to reproduce the issue, because it may work properly and in an hour accidentally stop working on the same device with the same data. 

env:
react-native@0.70.6
"react-native-navigation": "^7.32.1"
"@reduxjs/toolkit": "^1.9.3"
"react": "18.1.0"

Hope this helps

**Comment by rifad4u** [comment]
Hi RonRadtke/react-native-blob-util,

This issue is happening when the app opens for the first time or opens from
killed state , not happening this issue in between. means if you get proper
response when the app opens then this issue won’t come in this session.

**Comment by RonRadtke** [comment]
@rifad4u @emelyanova 
Thank you for the information.
Could you try to remove /comment out this line: 
https://github.com/RonRadtke/react-native-blob-util/blob/132051c1204051f5148a0b4bfede00ed99f47c44/index.js#L45
And see if youbstill can reproduce it?
I so far didn't manage to reproduce it at allregardless how often i try

**Comment by rifad4u** [comment]
> emitExpiredEvent

<img width="452" alt="Screenshot 2023-05-12 at 7 07 27 AM" src="https://github.com/RonRadtke/react-native-blob-util/assets/37132763/b31df817-8c15-4741-8326-8324091d85ee">

Commented the line , but still facing the same issue 😕.

**Comment by RonRadtke** [comment]
Too bad 😕
@rifad4u I assume you can't create an example repo for reproducing it either?
But I hope I get the new event emitting rework for ios done next week or the week after.
Maybe you could test if that helps once I'm done?

**Comment by rifad4u** [comment]
> Too bad 😕 @rifad4u I assume you can't create an example repo for reproducing it either? But I hope I get the new event emitting rework for ios done next week or the week after. Maybe you could test if that helps once I'm done?

I'm trying to reproduce the same in a new project.
meanwhile if you apply any fix you can comment here , i will check.

**Comment by RonRadtke** [comment]
Thank you.
Otherwise what could be interesting is if you have an eventdispatcher in this line or if it is e.g. null. So basically if the issue is somewhere there of in js
https://github.com/RonRadtke/react-native-blob-util/blob/132051c1204051f5148a0b4bfede00ed99f47c44/ios/ReactNativeBlobUtilRequest.mm#L273

**Comment by RonRadtke** [comment]
@rifad4u I got the ios part of the new eventemitter structure done and did a basic testing on it.
you can use it by setting the version of react-native-blob-util to "ronradtke/react-native-blob-util#feature/eventemitter_rework"

Would be great if you could test if you can reproduce the issue on that branch too.

**Comment by rifad4u** [comment]
> @rifad4u I got the ios part of the new eventemitter structure done and did a basic testing on it. you can use it by setting the version of react-native-blob-util to "ronradtke/react-native-blob-util#feature/eventemitter_rework"
> 
> Would be great if you could test if you can reproduce the issue on that branch too.

Hi @RonRadtke ,
Still facing the same issue , please find the screenshots below.
<img width="624" alt="Screenshot 2023-05-22 at 4 40 41 PM" src="https://github.com/RonRadtke/react-native-blob-util/assets/37132763/0b473dd8-f01f-4f42-8eb6-7dfd03e189b9">
<img width="631" alt="Screenshot 2023-05-22 at 4 40 53 PM" src="https://github.com/RonRadtke/react-native-blob-util/assets/37132763/ab7b7ffb-b3d3-40ae-932e-556e1cd6af5b">

**Comment by RonRadtke** [comment]
Both screenshots are the same request or what are you showing here?
Did you check if the event is being fired within the native code?

**Comment by RonRadtke** [comment]
Thank you! I committed a fix for it.
I missed a JSON.parse there..
The status code seems to be set correctly in the event that js is getting. It's set to 200. But please try again to confirm if it is working

**Comment by RonRadtke** [comment]
Great. I will try to finish the Android part this week and then hopefully get it live :)

**Comment by NishilE** [comment]
Hi, @RonRadtke, have you released the Android fix yet? I'm still having the same issue with version 0.19.4. The same issue happening for me as @rifad4u. I'm unable to get any responses on the first try after the app is opened. But It works when I kill the app and try again. I would be really grateful if you could give a reply as soon as possible since I'm blocked by the issue. Thank you for your effort and consideration.

**Comment by RonRadtke** [comment]
> Hi, @RonRadtke, have you released the Android fix yet? I'm still having the same issue with version 0.19.4. The same issue happening for me as @rifad4u. I'm unable to get any responses on the first try after the app is opened. But It works when I kill the app and try again. I would be really grateful if you could give a reply as soon as possible since I'm blocked by the issue. Thank you for your effort and consideration.

Yes I fixed aome problems here. But it could be we're running in some race conditions here, or, some problems during registration of the event listener.

**Comment by RonRadtke** [comment]
> > Hi, @RonRadtke, have you released the Android fix yet? I'm still having the same issue with version 0.19.4. The same issue happening for me as @rifad4u. I'm unable to get any responses on the first try after the app is opened. But It works when I kill the app and try again. I would be really grateful if you could give a reply as soon as possible since I'm blocked by the issue. Thank you for your effort and consideration.
> 
> Yes I fixed aome problems here. But it could be we're running in some race conditions here, or, some problems during registration of the event listener.

@NishilE you are facing problems on Android? The issue and fixed here are about ios...

**Comment by NishilE** [comment]
@RonRadtke, Yes I'm facing the issue in Android.

**Comment by jenipharachel** [comment]
@RonRadtke Which release contains the fix https://github.com/RonRadtke/react-native-blob-util/commit/9402e3a246a388150c961b8253c6ef0230b01fa2?

**Comment by jenipharachel** [comment]
Okay, for anyone facing an issue with version 0.17.0, Please check your yarn.lock file. For me, I thought i was using 0.17.0 but 0.17.3 was installed. So far, no issues but need to monitor and see till we release this to prod.
