### ISSUE TITLE
Cannot read property 'rnfbEncode' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by mMarcos208** [RonRadtke/react-native-blob-util#321]
My code

```
import {Platform} from 'react-native'
import ReactNativeBlobUtil, {ReactNativeBlobUtilConfig} from 'react-native-blob-util'


export const options = (name: string, extension = 'pdf', notification = true) => {
  const {fs} = ReactNativeBlobUtil
  const {
    dirs: {DocumentDir, DownloadDir},
  } = fs
  return Platform.select({
    ios: {
      fileCache: true,
      path: `${DocumentDir}/${name}`,
      title: name,
    },
    android: {
      fileCache: true,
      addAndroidDownloads: {
        useDownloadManager: true,
        notification,
        title: name,
        path: `${DownloadDir}/${name}.${extension}`,
      },
    },
  }) as ReactNativeBlobUtilConfig
}

```

```
import {useCallback, useState} from 'react'
import {Platform} from 'react-native'
import ReactNativeBlobUtil from 'react-native-blob-util'

import {options} from '@/utils/blob'
import {filesPermission} from '@/utils/hardwarePermissions'

export const useFetchBlob = () => {
  const [progress, setProgress] = useState<number>()

  const fetchBlob = useCallback(
    async (
      url: string,
      name: string,
      extension?: string,
      headers?: {
        [key: string]: string
      },
    ) => {
      try {
        const hasDownloadPermission = await filesPermission()
        if (hasDownloadPermission) {
          const {config} = ReactNativeBlobUtil

          const res = await config(options(name, extension))
            .fetch('GET', url, headers)
            .progress((received, total) => {
              setProgress(received / total)
            })

          if (Platform.OS === 'ios') {
            ReactNativeBlobUtil.ios.previewDocument(res.path())
          }
        } else {
        }
      } catch (error) {} finally {
        setProgress(undefined)
      }
    },
    [progress],
  )

  return {
    progress,
    fetchBlob,
  }
}


```

 "react-native": "0.72.7"
 "react-native-blob-util": "^0.19.6",

**Comment by Mohamed-Sheik-Ali** [comment]
Hi @mMarcos208 I think the issue is with package version, I also stumbled on the same error. So, I downgraded the version to `react-native-blob-util@0.19.4` it works for me. Hope it helps.

**Comment by RemiHin** [comment]
> Hi @mMarcos208 I think the issue is with package version, I also stumbled on the same error. So, I downgraded the version to `react-native-blob-util@0.19.4` it works for me. Hope it helps.

I have the same issue, reverting back to 0.19.4 solved it for now

**Comment by appa-gomi** [comment]
Comment the two line(273, 274) in fetch.js

```
                         fs.session(options.session).add(data);
                 }
                 respInfo.rnfbEncode = rawType;
-                if ('uninit' in respInfo && respInfo.uninit) // event didn't fire yet so we override it here
-                    respInfo = responseInfo;
+                // if ('uninit' in respInfo && respInfo.uninit) // event didn't fire yet so we override it here
+                //     respInfo = responseInfo;
                 resolve(new FetchBlobResponse(taskId, respInfo, data));
             }
```

**Comment by zehratok** [comment]
> Comment the two line(273, 274) in fetch.js
> 
> ```
>                          fs.session(options.session).add(data);
>                  }
>                  respInfo.rnfbEncode = rawType;
> -                if ('uninit' in respInfo && respInfo.uninit) // event didn't fire yet so we override it here
> -                    respInfo = responseInfo;
> +                // if ('uninit' in respInfo && respInfo.uninit) // event didn't fire yet so we override it here
> +                //     respInfo = responseInfo;
>                  resolve(new FetchBlobResponse(taskId, respInfo, data));
>              }
> ```
This method worked for me, thank you. However, I didn't understand why such a change was made in the package; the commit messages were not explanatory.

**Comment by MohamedMegdich1** [comment]
Hi @mMarcos208, I have fixed this issue by wrapping the path with **path: ReactNativeBlobUtil.wrap(filePath)**

import {Platform} from 'react-native'
import ReactNativeBlobUtil, {ReactNativeBlobUtilConfig} from 'react-native-blob-util'


export const options = (name: string, extension = 'pdf', notification = true) => {
  const {fs} = ReactNativeBlobUtil
  const {
    dirs: {DocumentDir, DownloadDir},
  } = fs
  return Platform.select({
    ios: {
      fileCache: true,
      path: `${DocumentDir}/${name}`,
      title: name,
    },
    android: {
      fileCache: true,
      addAndroidDownloads: {
        useDownloadManager: true,
        notification,
        title: name,
        path: ReactNativeBlobUtil.wrap( `${DownloadDir}/${name}.${extension}`),
      },
    },
  }) as ReactNativeBlobUtilConfig
}

**Comment by MohamedMegdich1** [comment]
`import`

**Comment by imanshul** [comment]
Any update? still facing this issue, and downgrading to 0.19.4 also doesn't resolve issue

**Comment by TheWirv** [comment]
> Comment the two line(273, 274) in fetch.js
> 
> ```
>                          fs.session(options.session).add(data);
>                  }
>                  respInfo.rnfbEncode = rawType;
> -                if ('uninit' in respInfo && respInfo.uninit) // event didn't fire yet so we override it here
> -                    respInfo = responseInfo;
> +                // if ('uninit' in respInfo && respInfo.uninit) // event didn't fire yet so we override it here
> +                //     respInfo = responseInfo;
>                  resolve(new FetchBlobResponse(taskId, respInfo, data));
>              }
> ```

This patch also fixed the issue for me, thanks!

**Comment by obinote** [comment]
> Comment the two line(273, 274) in fetch.js
> 
> ```
>                          fs.session(options.session).add(data);
>                  }
>                  respInfo.rnfbEncode = rawType;
> -                if ('uninit' in respInfo && respInfo.uninit) // event didn't fire yet so we override it here
> -                    respInfo = responseInfo;
> +                // if ('uninit' in respInfo && respInfo.uninit) // event didn't fire yet so we override it here
> +                //     respInfo = responseInfo;
>                  resolve(new FetchBlobResponse(taskId, respInfo, data));
>              }
> ```

It work for me.

**Comment by Sakib-203-15-3883** [comment]
> Hi @mMarcos208 I think the issue is with package version, I also stumbled on the same error. So, I downgraded the version to `react-native-blob-util@0.19.4` it works for me. Hope it helps.

It works for me.

**Comment by RonRadtke** [comment]
Can you tell me in which line this fails exactly?
Would like to fix this.

But to explain the changes.
There are cases where the native events are triggered after the callback is triggered. Therefor the callback gets all information and if the event happens to arrive after the callback we still can resolve with all required information.

Just that seems like I missed something

**Comment by maksimko** [comment]
In my case it only happens on Android. The same code on iOS works fine. 
Version 0.19.4 works well on both platforms.

**Comment by raymondjacobson** [comment]
+1 seeing this issue. 0.19.4 fixes it for me as well.

**Comment by endrits079** [comment]
> Hi @mMarcos208, I have fixed this issue by wrapping the path with **path: ReactNativeBlobUtil.wrap(filePath)**
> 
> ` import {Platform} from 'react-native' import ReactNativeBlobUtil, {ReactNativeBlobUtilConfig} from 'react-native-blob-util'
> 
> export const options = (name: string, extension = 'pdf', notification = true) => { const {fs} = ReactNativeBlobUtil const { dirs: {DocumentDir, DownloadDir}, } = fs return Platform.select({ ios: { fileCache: true, path: ReactNativeBlobUtil.wrap(`${DocumentDir}/${name}`), title: name, }, android: { fileCache: true, addAndroidDownloads: { useDownloadManager: true, notification, title: name, path: ReactNativeBlobUtil.wrap( `${DownloadDir}/${name}.${extension}`), }, }, }) as ReactNativeBlobUtilConfig } `

worked for me

**Comment by paskalov-aris** [comment]
> Hi @mMarcos208 I think the issue is with package version, I also stumbled on the same error. So, I downgraded the version to `react-native-blob-util@0.19.4` it works for me. Hope it helps.

Downgrading from 0.19.6 to 0.19.4 fixed the error in my case. Thanks.

**Comment by mMarcos208** [comment]
Downgrade to 0.19.4 cause this error https://github.com/RonRadtke/react-native-blob-util/issues/204

**Comment by RonRadtke** [comment]
@mMarcos208 @paskalov-aris  @endrits079 
Anyone can tell we whitch line is causing thw probelm?
And is it an on progress event or when the request os finished?
Android / ios / both?

**Comment by bhavdeep-pixer** [comment]
> Hi @mMarcos208 I think the issue is with package version, I also stumbled on the same error. So, I downgraded the version to `react-native-blob-util@0.19.4` it works for me. Hope it helps.

It's also worked for me. Thanks @Mohamed-Sheik-Ali

**Comment by RonRadtke** [comment]
> @mMarcos208 @paskalov-aris @endrits079 Anyone can tell we whitch line is causing the probelm? And is it an on progress event or when the request is finished? Android / ios / both?
> 
> Some more information to reproduce it would be great so you don't have to downgrade

@bhavdeep-pixer same question to you.

**Comment by herberthk** [comment]
> Hi @mMarcos208 I think the issue is with package version, I also stumbled on the same error. So, I downgraded the version to `react-native-blob-util@0.19.4` it works for me. Hope it helps.

Thanks solved my issue

**Comment by sadewole** [comment]
The file got downloaded but cannot locate it in the device file manager. It was downloaded to the internal app which is not visible.

How can this be fixed, please?
